"""
Seed mechanism list for the behavioral mechanisms knowledge base.

130 named mechanisms across 7 domains. Each entry:
  id          - snake_case identifier (corpus filename stem)
  name        - display name
  domain      - one of the 7 domains
  wikipedia   - Wikipedia article title to fetch via kiwix
  kagi_query  - search string for Kagi paper search
"""

DOMAINS = [
    "threat_affective_priming",
    "status_dominance",
    "loss_aversion_reference",
    "ingroup_outgroup",
    "posthoc_rationalization",
    "individual_variation",
    "social_influence_compliance",
]

SEEDS = [
    # ─── Domain 1: Threat / Affective Priming ────────────────────────────────
    {
        "id": "fight_flight_freeze",
        "name": "Fight-or-flight-or-freeze response",
        "domain": "threat_affective_priming",
        "wikipedia": "Fight-or-flight response",
        "kagi_query": "fight flight freeze stress response behavioral neuroscience",
    },
    {
        "id": "negativity_bias",
        "name": "Negativity bias",
        "domain": "threat_affective_priming",
        "wikipedia": "Negativity bias",
        "kagi_query": "negativity bias psychology effect size replication",
    },
    {
        "id": "hypervigilance",
        "name": "Hypervigilance",
        "domain": "threat_affective_priming",
        "wikipedia": "Hypervigilance",
        "kagi_query": "hypervigilance threat detection cognitive behavioral",
    },
    {
        "id": "affective_priming",
        "name": "Affective priming",
        "domain": "threat_affective_priming",
        "wikipedia": "Priming (psychology)",
        "kagi_query": "affective priming behavioral effects automatic evaluation",
    },
    {
        "id": "somatic_marker_hypothesis",
        "name": "Somatic marker hypothesis",
        "domain": "threat_affective_priming",
        "wikipedia": "Somatic marker hypothesis",
        "kagi_query": "Damasio somatic marker hypothesis decision making evidence",
    },
    {
        "id": "amygdala_threat_response",
        "name": "Amygdala threat response",
        "domain": "threat_affective_priming",
        "wikipedia": "Amygdala",
        "kagi_query": "amygdala threat response fear conditioning behavioral effects",
    },
    {
        "id": "anxiety_avoidance",
        "name": "Anxiety and avoidance behavior",
        "domain": "threat_affective_priming",
        "wikipedia": "Anxiety",
        "kagi_query": "anxiety behavioral avoidance inhibition neuroscience",
    },
    {
        "id": "stress_cognition",
        "name": "Stress effects on cognition and decision-making",
        "domain": "threat_affective_priming",
        "wikipedia": "Psychological stress",
        "kagi_query": "acute stress decision making cognitive impairment evidence",
    },
    # ─── Domain 2: Status and Dominance ──────────────────────────────────────
    {
        "id": "social_dominance_orientation",
        "name": "Social dominance orientation",
        "domain": "status_dominance",
        "wikipedia": "Social dominance orientation",
        "kagi_query": "social dominance orientation Sidanius Pratto behavioral outcomes",
    },
    {
        "id": "dominance_hierarchy",
        "name": "Dominance hierarchy",
        "domain": "status_dominance",
        "wikipedia": "Dominance hierarchy",
        "kagi_query": "dominance hierarchy social behavior human primate evidence",
    },
    {
        "id": "shame_response",
        "name": "Shame response",
        "domain": "status_dominance",
        "wikipedia": "Shame",
        "kagi_query": "shame behavioral response social status threat psychology",
    },
    {
        "id": "prestige_dominance",
        "name": "Prestige vs. dominance as dual routes to status",
        "domain": "status_dominance",
        "wikipedia": "Social status",
        "kagi_query": "prestige dominance dual routes status Henrich Gil-White evidence",
    },
    {
        "id": "costly_signaling",
        "name": "Costly signaling",
        "domain": "status_dominance",
        "wikipedia": "Signalling theory",
        "kagi_query": "costly signaling human behavior status honest signal",
    },
    {
        "id": "testosterone_status",
        "name": "Testosterone and status-seeking",
        "domain": "status_dominance",
        "wikipedia": "Testosterone",
        "kagi_query": "testosterone social status dominance competition behavioral effects",
    },
    {
        "id": "status_threat_response",
        "name": "Status threat response",
        "domain": "status_dominance",
        "wikipedia": "Status inconsistency",
        "kagi_query": "status threat response behavioral consequences social psychology",
    },
    {
        "id": "conformity_social_influence",
        "name": "Conformity and social influence",
        "domain": "status_dominance",
        "wikipedia": "Conformity",
        "kagi_query": "Asch conformity social influence effect size replication",
    },
    # ─── Domain 3: Loss Aversion and Reference Dependence ────────────────────
    {
        "id": "loss_aversion",
        "name": "Loss aversion",
        "domain": "loss_aversion_reference",
        "wikipedia": "Loss aversion",
        "kagi_query": "loss aversion prospect theory effect size replication behavioral economics",
    },
    {
        "id": "endowment_effect",
        "name": "Endowment effect",
        "domain": "loss_aversion_reference",
        "wikipedia": "Endowment effect",
        "kagi_query": "endowment effect Kahneman Knetsch Thaler replication behavioral economics",
    },
    {
        "id": "status_quo_bias",
        "name": "Status quo bias",
        "domain": "loss_aversion_reference",
        "wikipedia": "Status quo bias",
        "kagi_query": "status quo bias Samuelson Zeckhauser behavioral economics evidence",
    },
    {
        "id": "sunk_cost_fallacy",
        "name": "Sunk cost fallacy",
        "domain": "loss_aversion_reference",
        "wikipedia": "Sunk cost",
        "kagi_query": "sunk cost fallacy behavioral evidence decision making",
    },
    {
        "id": "prospect_theory",
        "name": "Prospect theory and reference point dependence",
        "domain": "loss_aversion_reference",
        "wikipedia": "Prospect theory",
        "kagi_query": "prospect theory Kahneman Tversky reference dependence experimental evidence",
    },
    {
        "id": "mental_accounting",
        "name": "Mental accounting",
        "domain": "loss_aversion_reference",
        "wikipedia": "Mental accounting",
        "kagi_query": "mental accounting Thaler behavioral economics experimental evidence",
    },
    {
        "id": "anchoring_bias",
        "name": "Anchoring bias",
        "domain": "loss_aversion_reference",
        "wikipedia": "Anchoring (cognitive bias)",
        "kagi_query": "anchoring cognitive bias effect size replication Tversky Kahneman",
    },
    {
        "id": "risk_aversion",
        "name": "Risk aversion",
        "domain": "loss_aversion_reference",
        "wikipedia": "Risk aversion",
        "kagi_query": "risk aversion behavioral decision making individual differences",
    },
    # ─── Domain 4: In-group / Out-group ──────────────────────────────────────
    {
        "id": "minimal_group_paradigm",
        "name": "Minimal group paradigm",
        "domain": "ingroup_outgroup",
        "wikipedia": "Minimal group paradigm",
        "kagi_query": "minimal group paradigm Tajfel Turner social identity replication",
    },
    {
        "id": "in_group_favoritism",
        "name": "In-group favoritism",
        "domain": "ingroup_outgroup",
        "wikipedia": "In-group favoritism",
        "kagi_query": "in-group favoritism behavioral effects social psychology evidence",
    },
    {
        "id": "out_group_homogeneity",
        "name": "Out-group homogeneity effect",
        "domain": "ingroup_outgroup",
        "wikipedia": "Out-group homogeneity",
        "kagi_query": "out-group homogeneity effect perception social psychology",
    },
    {
        "id": "social_identity_theory",
        "name": "Social identity theory",
        "domain": "ingroup_outgroup",
        "wikipedia": "Social identity theory",
        "kagi_query": "social identity theory Tajfel Turner behavioral predictions evidence",
    },
    {
        "id": "contact_hypothesis",
        "name": "Intergroup contact hypothesis",
        "domain": "ingroup_outgroup",
        "wikipedia": "Contact hypothesis",
        "kagi_query": "intergroup contact hypothesis Allport meta-analysis effect size",
    },
    {
        "id": "dehumanization",
        "name": "Dehumanization",
        "domain": "ingroup_outgroup",
        "wikipedia": "Dehumanization",
        "kagi_query": "dehumanization psychological mechanisms behavioral effects out-group",
    },
    {
        "id": "moral_exclusion",
        "name": "Moral exclusion",
        "domain": "ingroup_outgroup",
        "wikipedia": "Moral disengagement",
        "kagi_query": "moral exclusion Opotow out-group harm justification behavioral",
    },
    {
        "id": "scapegoating",
        "name": "Scapegoating",
        "domain": "ingroup_outgroup",
        "wikipedia": "Scapegoating",
        "kagi_query": "scapegoating behavioral psychology frustration aggression out-group",
    },
    # ─── Domain 5: Post-hoc Rationalization / Motivated Reasoning ────────────
    {
        "id": "confabulation",
        "name": "Confabulation",
        "domain": "posthoc_rationalization",
        "wikipedia": "Confabulation",
        "kagi_query": "confabulation post-hoc rationalization behavioral neuroscience evidence",
    },
    {
        "id": "motivated_reasoning",
        "name": "Motivated reasoning",
        "domain": "posthoc_rationalization",
        "wikipedia": "Motivated reasoning",
        "kagi_query": "motivated reasoning Kunda directional goals behavioral evidence",
    },
    {
        "id": "confirmation_bias",
        "name": "Confirmation bias",
        "domain": "posthoc_rationalization",
        "wikipedia": "Confirmation bias",
        "kagi_query": "confirmation bias Nickerson effect size replication evidence",
    },
    {
        "id": "moral_dumbfounding",
        "name": "Moral dumbfounding",
        "domain": "posthoc_rationalization",
        "wikipedia": "Moral dumbfounding",
        "kagi_query": "moral dumbfounding Haidt moral reasoning confabulation evidence",
    },
    {
        "id": "cognitive_dissonance",
        "name": "Cognitive dissonance",
        "domain": "posthoc_rationalization",
        "wikipedia": "Cognitive dissonance",
        "kagi_query": "cognitive dissonance Festinger replication behavioral effects",
    },
    {
        "id": "belief_perseverance",
        "name": "Belief perseverance",
        "domain": "posthoc_rationalization",
        "wikipedia": "Belief perseverance",
        "kagi_query": "belief perseverance continued influence effect replication",
    },
    {
        "id": "self_serving_bias",
        "name": "Self-serving bias",
        "domain": "posthoc_rationalization",
        "wikipedia": "Self-serving bias",
        "kagi_query": "self-serving bias attribution effect size cross-cultural evidence",
    },
    {
        "id": "hindsight_bias",
        "name": "Hindsight bias",
        "domain": "posthoc_rationalization",
        "wikipedia": "Hindsight bias",
        "kagi_query": "hindsight bias knew-it-all-along Fischhoff meta-analysis",
    },
    {
        "id": "choice_blindness",
        "name": "Choice blindness",
        "domain": "posthoc_rationalization",
        "wikipedia": "Choice blindness",
        "kagi_query": "choice blindness Hall Johansson post-hoc rationalization",
    },
    {
        "id": "social_intuitionist_model",
        "name": "Social intuitionist model of moral judgment",
        "domain": "posthoc_rationalization",
        "wikipedia": "Jonathan Haidt",
        "kagi_query": "Haidt social intuitionist model moral judgment post-hoc reasoning evidence",
    },
    # ─── Domain 6: Individual Variation Dimensions ────────────────────────────
    {
        "id": "big_five_personality",
        "name": "Big Five personality traits",
        "domain": "individual_variation",
        "wikipedia": "Big Five personality traits",
        "kagi_query": "Big Five personality traits behavioral prediction heritability evidence",
    },
    {
        "id": "dark_triad",
        "name": "Dark triad",
        "domain": "individual_variation",
        "wikipedia": "Dark triad",
        "kagi_query": "dark triad narcissism Machiavellianism psychopathy behavioral outcomes",
    },
    {
        "id": "disgust_sensitivity",
        "name": "Disgust sensitivity",
        "domain": "individual_variation",
        "wikipedia": "Disgust",
        "kagi_query": "disgust sensitivity individual differences moral judgment behavioral effects",
    },
    {
        "id": "sensory_processing_sensitivity",
        "name": "Sensory processing sensitivity (high sensitivity)",
        "domain": "individual_variation",
        "wikipedia": "Sensory processing sensitivity",
        "kagi_query": "sensory processing sensitivity Aron highly sensitive person behavioral evidence",
    },
    {
        "id": "alexithymia",
        "name": "Alexithymia",
        "domain": "individual_variation",
        "wikipedia": "Alexithymia",
        "kagi_query": "alexithymia emotional processing behavioral outcomes prevalence",
    },
    {
        "id": "attachment_styles",
        "name": "Attachment styles",
        "domain": "individual_variation",
        "wikipedia": "Attachment theory",
        "kagi_query": "attachment styles adult behavioral outcomes Bowlby Ainsworth evidence",
    },
    {
        "id": "need_for_cognition",
        "name": "Need for cognition",
        "domain": "individual_variation",
        "wikipedia": "Need for cognition",
        "kagi_query": "need for cognition Cacioppo Petty individual differences behavioral outcomes",
    },
    {
        "id": "need_for_closure",
        "name": "Need for cognitive closure",
        "domain": "individual_variation",
        "wikipedia": "Need for closure",
        "kagi_query": "need for cognitive closure Webster Kruglanski behavioral effects",
    },
    {
        "id": "behavioral_inhibition_activation",
        "name": "Behavioral inhibition / activation systems (BIS/BAS)",
        "domain": "individual_variation",
        "wikipedia": "Reinforcement sensitivity theory",
        "kagi_query": "BIS BAS Gray reinforcement sensitivity behavioral inhibition activation individual differences",
    },
    {
        "id": "reward_sensitivity",
        "name": "Reward sensitivity and impulsivity",
        "domain": "individual_variation",
        "wikipedia": "Impulsivity",
        "kagi_query": "reward sensitivity impulsivity individual differences behavioral prediction",
    },
    # ─── Domain 7: Social Influence and Compliance ────────────────────────────
    {
        "id": "reciprocity",
        "name": "Reciprocity norm",
        "domain": "social_influence_compliance",
        "wikipedia": "Reciprocity (social psychology)",
        "kagi_query": "reciprocity norm social exchange obligation Gouldner Cialdini behavioral evidence",
    },
    {
        "id": "commitment_consistency",
        "name": "Commitment and consistency",
        "domain": "social_influence_compliance",
        "wikipedia": "Escalation of commitment",
        "kagi_query": "commitment consistency foot-in-the-door Cialdini self-perception behavioral evidence",
    },
    {
        "id": "obedience_authority",
        "name": "Obedience to authority",
        "domain": "social_influence_compliance",
        "wikipedia": "Milgram experiment",
        "kagi_query": "Milgram obedience authority situational factors replication behavioral",
    },
    {
        "id": "bystander_effect",
        "name": "Bystander effect and diffusion of responsibility",
        "domain": "social_influence_compliance",
        "wikipedia": "Bystander effect",
        "kagi_query": "bystander effect diffusion responsibility Darley Latané meta-analysis",
    },
    {
        "id": "social_proof",
        "name": "Social proof",
        "domain": "social_influence_compliance",
        "wikipedia": "Social proof",
        "kagi_query": "social proof informational influence conformity Cialdini behavioral evidence",
    },
    {
        "id": "reactance",
        "name": "Psychological reactance",
        "domain": "social_influence_compliance",
        "wikipedia": "Reactance (psychology)",
        "kagi_query": "psychological reactance Brehm autonomy threat behavioral boomerang effect",
    },
    # ─── Additions: threat_affective_priming ─────────────────────────────────
    {
        "id": "emotional_contagion",
        "name": "Emotional contagion",
        "domain": "threat_affective_priming",
        "wikipedia": "Emotional contagion",
        "kagi_query": "emotional contagion automatic mood transfer mimicry Hatfield evidence",
    },
    {
        "id": "terror_management",
        "name": "Terror management and mortality salience",
        "domain": "threat_affective_priming",
        "wikipedia": "Terror management theory",
        "kagi_query": "terror management theory mortality salience worldview defense Greenberg Pyszczynski Solomon",
    },
    {
        "id": "scarcity_mindset",
        "name": "Scarcity mindset and cognitive tunneling",
        "domain": "threat_affective_priming",
        "wikipedia": "Scarcity (social psychology)",
        "kagi_query": "scarcity mindset cognitive tunneling bandwidth Mullainathan Shafir behavioral evidence",
    },
    # ─── Additions: status_dominance ─────────────────────────────────────────
    {
        "id": "envy_jealousy",
        "name": "Envy and jealousy as behavioral drivers",
        "domain": "status_dominance",
        "wikipedia": "Envy",
        "kagi_query": "envy jealousy social comparison behavioral outcomes hostility sabotage motivation",
    },
    {
        "id": "power_effects",
        "name": "Power effects on cognition and behavior",
        "domain": "status_dominance",
        "wikipedia": "Power (social and political)",
        "kagi_query": "power effects perspective-taking approach inhibition Galinsky Keltner behavioral evidence",
    },
    {
        "id": "social_comparison",
        "name": "Social comparison theory",
        "domain": "status_dominance",
        "wikipedia": "Social comparison theory",
        "kagi_query": "social comparison theory Festinger upward downward behavioral effects self-evaluation",
    },
    # ─── Additions: posthoc_rationalization ──────────────────────────────────
    {
        "id": "fundamental_attribution_error",
        "name": "Fundamental attribution error and actor-observer asymmetry",
        "domain": "posthoc_rationalization",
        "wikipedia": "Fundamental attribution error",
        "kagi_query": "fundamental attribution error Ross actor-observer asymmetry cross-cultural replication",
    },
    {
        "id": "moral_licensing",
        "name": "Moral licensing",
        "domain": "posthoc_rationalization",
        "wikipedia": "Moral self-licensing",
        "kagi_query": "moral licensing self-licensing prior virtue subsequent transgression behavioral evidence replication",
    },
    {
        "id": "naive_realism",
        "name": "Naive realism",
        "domain": "posthoc_rationalization",
        "wikipedia": "Naïve realism (psychology)",
        "kagi_query": "naive realism Ross Ward psychological bias disagreement attribution behavioral",
    },
    # ─── Additions: loss_aversion_reference ──────────────────────────────────
    {
        "id": "cognitive_load_dual_process",
        "name": "Cognitive load and dual-process reasoning",
        "domain": "loss_aversion_reference",
        "wikipedia": "Dual process theory",
        "kagi_query": "dual process theory System 1 System 2 cognitive load decision making Kahneman Evans",
    },
    # ─── Additions: status_dominance ─────────────────────────────────────────
    {
        "id": "pride",
        "name": "Pride and hubristic vs. authentic pride",
        "domain": "status_dominance",
        "wikipedia": "Pride",
        "kagi_query": "pride emotion behavioral effects status display hubristic authentic Tracy Robins",
    },
    {
        "id": "impression_management",
        "name": "Impression management and self-presentation",
        "domain": "status_dominance",
        "wikipedia": "Impression management",
        "kagi_query": "impression management self-presentation Goffman strategic behavioral social identity",
    },
    {
        "id": "mating_motivation",
        "name": "Mating motivation and its behavioral effects",
        "domain": "status_dominance",
        "wikipedia": "Human mating strategies",
        "kagi_query": "mating motives sexual motivation risk-taking resource display decision making Griskevicius Ariely",
    },
    {
        "id": "institutional_role_adoption",
        "name": "Institutional role adoption",
        "domain": "status_dominance",
        "wikipedia": "Stanford prison experiment",
        "kagi_query": "institutional role adoption Zimbardo Jackall situational behavior role identity moral disengagement",
    },
    # ─── Additions: threat_affective_priming ─────────────────────────────────
    {
        "id": "social_pain",
        "name": "Social pain and ostracism response",
        "domain": "threat_affective_priming",
        "wikipedia": "Ostracism",
        "kagi_query": "social pain rejection neural mechanisms Eisenberger Williams ostracism behavioral effects",
    },
    {
        "id": "loneliness",
        "name": "Loneliness and hypervigilance to social threat",
        "domain": "threat_affective_priming",
        "wikipedia": "Loneliness",
        "kagi_query": "loneliness behavioral effects hypervigilance social threat Cacioppo cognitive effects",
    },
    {
        "id": "curiosity_exploration",
        "name": "Curiosity and exploratory behavior",
        "domain": "threat_affective_priming",
        "wikipedia": "Curiosity",
        "kagi_query": "curiosity exploratory behavior intrinsic motivation novelty approach Berlyne Litman behavioral",
    },
    {
        "id": "hot_cold_empathy_gap",
        "name": "Hot-cold empathy gap",
        "domain": "threat_affective_priming",
        "wikipedia": "Empathy gap",
        "kagi_query": "hot cold empathy gap visceral states decision making Loewenstein arousal hunger prediction failure",
    },
    # ─── Additions: ingroup_outgroup ──────────────────────────────────────────
    {
        "id": "coalition_formation",
        "name": "Coalition formation and alliance dynamics",
        "domain": "ingroup_outgroup",
        "wikipedia": "Coalition",
        "kagi_query": "coalition formation alliance dynamics shared threat social exchange evolutionary behavioral",
    },
    # ─── Additions: posthoc_rationalization ──────────────────────────────────
    {
        "id": "self_handicapping",
        "name": "Self-handicapping",
        "domain": "posthoc_rationalization",
        "wikipedia": "Self-handicapping",
        "kagi_query": "self-handicapping advance excuse self-image protection Berglas Jones behavioral evidence",
    },
    # ─── Additions: loss_aversion_reference ──────────────────────────────────
    {
        "id": "habit",
        "name": "Habit formation and behavioral automaticity",
        "domain": "loss_aversion_reference",
        "wikipedia": "Habit (psychology)",
        "kagi_query": "habit formation automaticity cue routine reward Wood Neal behavioral inertia",
    },
    # ─── Additions: social_influence_compliance ───────────────────────────────
    {
        "id": "trust_formation",
        "name": "Trust formation and repair",
        "domain": "social_influence_compliance",
        "wikipedia": "Trust (social science)",
        "kagi_query": "trust formation repair betrayal behavioral mechanisms sequential investment Camerer",
    },
    {
        "id": "forgiveness",
        "name": "Forgiveness and transgression repair",
        "domain": "social_influence_compliance",
        "wikipedia": "Forgiveness",
        "kagi_query": "forgiveness psychology conditional apology repair relationship cost McCullough Worthington",
    },
    {
        "id": "deception_lying",
        "name": "Deception and lying",
        "domain": "social_influence_compliance",
        "wikipedia": "Deception",
        "kagi_query": "deception lying behavioral triggers frequency detection individual differences DePaulo",
    },
    {
        "id": "sycophancy",
        "name": "Sycophancy and upward management",
        "domain": "social_influence_compliance",
        "wikipedia": "Sycophancy",
        "kagi_query": "sycophancy upward management ingratiation Jackall organizational impression hierarchy behavioral",
    },
    # ─── Additions: individual_variation ─────────────────────────────────────
    {
        "id": "need_for_uniqueness",
        "name": "Need for uniqueness and contrarianism",
        "domain": "individual_variation",
        "wikipedia": "Need for uniqueness",
        "kagi_query": "need for uniqueness Snyder Fromkin contrarianism nonconformity individual differences behavioral",
    },
    # ─── Additions: social_influence_compliance ───────────────────────────────
    {
        "id": "pluralistic_ignorance",
        "name": "Pluralistic ignorance",
        "domain": "social_influence_compliance",
        "wikipedia": "Pluralistic ignorance",
        "kagi_query": "pluralistic ignorance norm persistence private rejection public compliance Prentice Miller behavioral",
    },
    # ─── Additions: threat_affective_priming ─────────────────────────────────
    {
        "id": "learned_helplessness",
        "name": "Learned helplessness",
        "domain": "threat_affective_priming",
        "wikipedia": "Learned helplessness",
        "kagi_query": "learned helplessness Seligman uncontrollable outcomes behavioral passivity depression evidence",
    },
    # ─── Additions: posthoc_rationalization ──────────────────────────────────
    {
        "id": "positive_illusions",
        "name": "Positive illusions and unrealistic optimism",
        "domain": "posthoc_rationalization",
        "wikipedia": "Positive illusions",
        "kagi_query": "positive illusions unrealistic optimism Taylor Brown self-enhancement mental health behavioral",
    },
    # ─── Additions: incel/polarization research ───────────────────────────────
    {
        "id": "affective_polarization",
        "name": "Affective polarization",
        "domain": "ingroup_outgroup",
        "wikipedia": "Affective polarization",
        "kagi_query": "affective polarization partisan hostility Iyengar Westwood behavioral consequences discrimination Mason sorting",
    },
    {
        "id": "identity_fusion",
        "name": "Identity fusion",
        "domain": "ingroup_outgroup",
        "wikipedia": "Identity fusion",
        "kagi_query": "identity fusion Swann extreme pro-group behavior self-sacrifice versus identification empirical meta-analysis",
    },
    {
        "id": "collective_narcissism",
        "name": "Collective narcissism",
        "domain": "ingroup_outgroup",
        "wikipedia": "Collective narcissism",
        "kagi_query": "collective narcissism Golec de Zavala ingroup exceptionalism recognition hostility conspiracy behavioral",
    },
    {
        "id": "identity_protective_cognition",
        "name": "Identity-protective cognition",
        "domain": "posthoc_rationalization",
        "wikipedia": "Cultural cognition",
        "kagi_query": "identity protective cognition Kahan cultural cognition smart idiot analytic ability polarization",
    },
    {
        "id": "myside_bias",
        "name": "Myside bias",
        "domain": "posthoc_rationalization",
        "wikipedia": "Myside bias",
        "kagi_query": "myside bias Stanovich cognitive ability uncorrelated argument generation evaluation evidence epistemic",
    },
    {
        "id": "sacred_values",
        "name": "Sacred values and protected value intransigence",
        "domain": "posthoc_rationalization",
        "wikipedia": "Sacred values",
        "kagi_query": "sacred values protected values taboo trade-offs moral outrage intransigence Tetlock Baron Atran",
    },
    {
        "id": "significance_quest",
        "name": "Significance quest and need for personal significance",
        "domain": "threat_affective_priming",
        "wikipedia": "Significance quest theory",
        "kagi_query": "significance quest theory Kruglanski need significance radicalization extremism 3N model behavioral",
    },
    {
        "id": "precarious_manhood",
        "name": "Precarious manhood and masculinity threat response",
        "domain": "status_dominance",
        "wikipedia": "Precarious manhood",
        "kagi_query": "precarious manhood Vandello Bosson masculinity threat compensatory aggression risk-taking behavioral evidence",
    },
    # ─── Additions: conspiracy / propaganda ──────────────────────────────────
    {
        "id": "proportionality_bias",
        "name": "Proportionality bias",
        "domain": "posthoc_rationalization",
        "wikipedia": "Proportionality bias",
        "kagi_query": "proportionality bias big events big causes conspiracy thinking Leman Cinnirella Whitson Galinsky illusory pattern",
    },
    {
        "id": "illusory_truth_effect",
        "name": "Illusory truth effect",
        "domain": "social_influence_compliance",
        "wikipedia": "Illusory truth effect",
        "kagi_query": "illusory truth effect repetition fluency belief Hasher Goldstein Toppino Dechene Fazio meta-analysis replication",
    },
    # ─── Additions: 2026 zeitgeist ────────────────────────────────────────────
    {
        "id": "automation_bias",
        "name": "Automation bias and algorithm trust",
        "domain": "posthoc_rationalization",
        "wikipedia": "Automation bias",
        "kagi_query": "automation bias algorithm trust Mosier Skitka AI over-reliance error detection human factors behavioral",
    },
    {
        "id": "parasocial_attachment",
        "name": "Parasocial attachment and one-sided relationship simulation",
        "domain": "social_influence_compliance",
        "wikipedia": "Parasocial interaction",
        "kagi_query": "parasocial relationship attachment Horton Wohl media figures influencer one-sided bond behavioral effects meta-analysis",
    },
    # ─── Additions: individual_variation ─────────────────────────────────────
    {
        "id": "achievement_motivation",
        "name": "Achievement motivation (need for achievement)",
        "domain": "individual_variation",
        "wikipedia": "Need for achievement",
        "kagi_query": "need for achievement McClelland nAch mastery motivation behavioral persistence challenge preference individual differences",
    },
    {
        "id": "intrinsic_motivation_sdt",
        "name": "Intrinsic motivation and overjustification effect (SDT)",
        "domain": "individual_variation",
        "wikipedia": "Self-determination theory",
        "kagi_query": "intrinsic motivation overjustification effect Deci Ryan self-determination theory crowding out external reward behavioral",
    },
    # ─── Additions: risk / safety ─────────────────────────────────────────────
    {
        "id": "risk_compensation",
        "name": "Risk compensation and risk homeostasis",
        "domain": "loss_aversion_reference",
        "wikipedia": "Risk compensation",
        "kagi_query": "risk compensation risk homeostasis Wilde Peltzman effect safety measures behavioral adaptation target risk level",
    },
    # ─── Additions: affective / prosocial gaps ────────────────────────────────
    # These six fill confirmed zero-coverage gaps identified via ATOMIC analysis:
    # grateful/thankful, guilty/ashamed/apologizes, disappointed/regret,
    # cries/mourns, generous/loving/inspired, nostalgic — all absent from
    # all existing mechanisms' output vocabulary.
    {
        "id": "gratitude",
        "name": "Gratitude and its behavioral effects",
        "domain": "social_influence_compliance",
        "wikipedia": "Gratitude",
        "kagi_query": "gratitude behavioral effects prosocial reciprocity McCullough Fredrickson broaden-and-build find-remind-bind",
    },
    {
        "id": "guilt",
        "name": "Guilt and reparative behavior",
        "domain": "posthoc_rationalization",
        "wikipedia": "Guilt (emotion)",
        "kagi_query": "guilt reparative behavior apology approach motivation Tangney Tracy self-conscious emotion distinct from shame",
    },
    {
        "id": "counterfactual_thinking",
        "name": "Counterfactual thinking and regret",
        "domain": "posthoc_rationalization",
        "wikipedia": "Counterfactual thinking",
        "kagi_query": "counterfactual thinking regret upward downward Roese Kahneman Miller near-miss behavioral consequences motivation",
    },
    {
        "id": "grief_bereavement",
        "name": "Grief and bereavement",
        "domain": "threat_affective_priming",
        "wikipedia": "Grief",
        "kagi_query": "grief bereavement stages Bowlby attachment disruption protest despair detachment behavioral Kübler-Ross Shear evidence",
    },
    {
        "id": "moral_elevation",
        "name": "Moral elevation and witnessing virtue",
        "domain": "social_influence_compliance",
        "wikipedia": "Elevation (emotion)",
        "kagi_query": "moral elevation Haidt witnessing virtue prosocial cascade feeling moved helping behavior Algoe Haidt Vasquez",
    },
    {
        "id": "nostalgia",
        "name": "Nostalgia and its social-psychological effects",
        "domain": "threat_affective_priming",
        "wikipedia": "Nostalgia",
        "kagi_query": "nostalgia social connectedness meaning buffering Sedikides Wildschut Arndt behavioral effects wellbeing",
    },
    # ─── Physiological state effects ─────────────────────────────────────────
    {
        "id": "hunger_effects",
        "name": "Hunger and glucose depletion effects on behavior",
        "domain": "individual_variation",
        "wikipedia": "Hunger (motivational state)",
        "kagi_query": "hunger glucose depletion decision making self-control impulsivity irritability Gailliot Baumeister ego depletion food deprivation behavioral effects cross-domain",
    },
    {
        "id": "sleep_deprivation_effects",
        "name": "Sleep deprivation and its behavioral consequences",
        "domain": "individual_variation",
        "wikipedia": "Sleep deprivation",
        "kagi_query": "sleep deprivation decision making risk taking impulsivity emotional reactivity cognitive performance behavioral consequences Walker Van Dongen Dinges",
    },
    # ─── Environmental / ambient state effects ────────────────────────────────
    {
        "id": "co2_air_quality",
        "name": "CO2 and air quality effects on cognition and decision making",
        "domain": "individual_variation",
        "wikipedia": "Indoor air quality",
        "kagi_query": "CO2 carbon dioxide indoor cognitive performance decision making Satish 2012 Harvard CHHE ventilation impairment 1000ppm office workers behavioral effects",
    },
    {
        "id": "ambient_noise",
        "name": "Ambient noise effects on cognition and creativity",
        "domain": "individual_variation",
        "wikipedia": "Noise pollution",
        "kagi_query": "ambient noise creativity cognitive performance Mehta 2012 Journal Consumer Research moderate noise 70dB working memory open office distraction creativity boost",
    },
    {
        "id": "nature_exposure_restoration",
        "name": "Nature exposure and attention restoration",
        "domain": "threat_affective_priming",
        "wikipedia": "Attention restoration theory",
        "kagi_query": "attention restoration theory Kaplan Kaplan nature exposure directed attention fatigue restoration involuntary attention green space hospital window stress recovery Ulrich",
    },
    # ─── Proxemics / space ────────────────────────────────────────────────────
    {
        "id": "proxemics_personal_space",
        "name": "Proxemics and personal space violation",
        "domain": "threat_affective_priming",
        "wikipedia": "Proxemics",
        "kagi_query": "proxemics personal space violation Hall stress arousal aggression discomfort interpersonal distance cultural variation behavioral response invasion",
    },
    # ─── Psychoactive substance effects ──────────────────────────────────────
    {
        "id": "alcohol_myopia",
        "name": "Alcohol myopia and intoxication effects on behavior",
        "domain": "individual_variation",
        "wikipedia": "Alcohol myopia",
        "kagi_query": "alcohol myopia Steele Josephs 1990 attentional narrowing intoxication aggression prosocial disinhibition impulsivity risk taking behavioral consequences",
    },
    {
        "id": "stimulant_effects",
        "name": "Stimulant drugs: behavioral and cognitive effects",
        "domain": "individual_variation",
        "wikipedia": "Stimulant",
        "kagi_query": "stimulant effects amphetamine cocaine behavioral cognition confidence risk taking social dominance impulsivity reward sensitivity dopamine behavioral pharmacology",
    },
    {
        "id": "cannabis_effects",
        "name": "Cannabis: behavioral and cognitive effects",
        "domain": "individual_variation",
        "wikipedia": "Effects of cannabis",
        "kagi_query": "cannabis behavioral effects THC decision making risk aversion time perception social cognition anxiety paranoia dose-dependent memory impairment",
    },
    {
        "id": "psychedelic_effects",
        "name": "Psychedelics: acute behavioral and social effects",
        "domain": "individual_variation",
        "wikipedia": "Psychedelic drug",
        "kagi_query": "psilocybin LSD MDMA behavioral effects social cognition openness ego dissolution prosocial behavior emotional reactivity acute psychological effects",
    },
    {
        "id": "caffeine_effects",
        "name": "Caffeine: arousal, attention, and anxiety effects",
        "domain": "individual_variation",
        "wikipedia": "Caffeine",
        "kagi_query": "caffeine behavioral effects attention arousal anxiety adenosine antagonism dose-dependent performance anxiety sensitivity individual differences",
    },
    # ─── Other empirical gaps ──────────────────────────────────────────────────
    {
        "id": "mere_exposure_effect",
        "name": "Mere exposure effect and familiarity-based preference",
        "domain": "posthoc_rationalization",
        "wikipedia": "Mere-exposure effect",
        "kagi_query": "mere exposure effect Zajonc 1968 familiarity preference liking subliminal exposure implicit attitude formation cross-cultural replication advertising",
    },
    {
        "id": "social_facilitation",
        "name": "Social facilitation and audience effects on performance",
        "domain": "individual_variation",
        "wikipedia": "Social facilitation",
        "kagi_query": "social facilitation Zajonc 1965 audience coaction dominant response arousal simple complex task performance evaluation apprehension distraction conflict",
    },
    {
        "id": "peak_end_rule",
        "name": "Peak-end rule and the memory-experience gap",
        "domain": "loss_aversion_reference",
        "wikipedia": "Peak–end rule",
        "kagi_query": "peak end rule Kahneman Fredrickson colonoscopy memory experience utility duration neglect cold pressor evaluation retrospective rating behavioral consequences",
    },
    # ─── Additions: loss_aversion_reference (temporal / construal) ───────────
    {
        "id": "temporal_discounting",
        "name": "Temporal discounting and delay of gratification",
        "domain": "loss_aversion_reference",
        "wikipedia": "Delay discounting",
        "kagi_query": "temporal discounting delay gratification Ainslie Mazur hyperbolic discounting impulsivity behavioral economics",
    },
    {
        "id": "construal_level_theory",
        "name": "Construal level theory",
        "domain": "loss_aversion_reference",
        "wikipedia": "Construal level theory",
        "kagi_query": "construal level theory Trope Liberman 2010 psychological distance abstract concrete near far behavioral effects",
    },
    # ─── Additions: posthoc_rationalization (effort / spotlight / planning) ──
    {
        "id": "effort_justification",
        "name": "Effort justification and the IKEA effect",
        "domain": "posthoc_rationalization",
        "wikipedia": "IKEA effect",
        "kagi_query": "IKEA effect effort justification Norton Mochon Ariely 2012 labor leads to love overvaluation behavioral evidence",
    },
    {
        "id": "spotlight_effect",
        "name": "Spotlight effect",
        "domain": "posthoc_rationalization",
        "wikipedia": "Spotlight effect (psychology)",
        "kagi_query": "spotlight effect Gilovich 2000 overestimating social scrutiny egocentric bias behavioral evidence",
    },
    {
        "id": "planning_fallacy",
        "name": "Planning fallacy",
        "domain": "posthoc_rationalization",
        "wikipedia": "Planning fallacy",
        "kagi_query": "planning fallacy Kahneman Buehler inside view outside view optimism bias time estimation behavioral evidence",
    },
    # ─── Additions: social_influence_compliance (punishment / gossip) ────────
    {
        "id": "altruistic_punishment",
        "name": "Altruistic punishment and third-party norm enforcement",
        "domain": "social_influence_compliance",
        "wikipedia": "Altruistic punishment",
        "kagi_query": "altruistic punishment Fehr Gachter 2002 public goods game costly punishment norm enforcement behavioral evidence",
    },
    {
        "id": "gossip_reputation",
        "name": "Gossip and reputation management",
        "domain": "social_influence_compliance",
        "wikipedia": "Gossip",
        "kagi_query": "gossip reputation management Dunbar Feinberg Willer norm policing indirect reciprocity behavioral evidence",
    },
    # ─── Additions: ingroup_outgroup (moral contagion) ──────────────────────
    {
        "id": "moral_contagion",
        "name": "Moral contagion and purity thinking",
        "domain": "ingroup_outgroup",
        "wikipedia": "Moral contagion",
        "kagi_query": "moral contagion Rozin Haidt contamination purity disgust moral judgment behavioral evidence",
    },
    # ─── Additions: inverse-trait / negative-dimension mechanisms ──────────────
    # These activate primarily for the "-" end of dimensions, filling gaps where
    # the knowledge base is biased toward "+" activation.
    {
        "id": "tend_and_befriend",
        "name": "Tend-and-befriend stress response",
        "domain": "individual_variation",
        "wikipedia": "Tend and befriend",
        "kagi_query": "tend and befriend Taylor 2000 oxytocin stress response affiliation caregiving prosocial alternative fight-flight behavioral evidence",
    },
    {
        "id": "communal_orientation",
        "name": "Communal orientation and relational self-construal",
        "domain": "individual_variation",
        "wikipedia": "Communal orientation",
        "kagi_query": "communal orientation Clark Mills exchange versus communal relationships relational self-construal responsiveness need behavioral",
    },
    {
        "id": "intellectual_humility",
        "name": "Intellectual humility and epistemic openness",
        "domain": "individual_variation",
        "wikipedia": "Intellectual humility",
        "kagi_query": "intellectual humility Leary epistemic openness recognizing limits belief revision disagreement tolerance behavioral evidence",
    },
    {
        "id": "moral_elevation",
        "name": "Moral elevation and upward moral emotion",
        "domain": "social_influence_compliance",
        "wikipedia": "Elevation (emotion)",
        "kagi_query": "moral elevation Haidt upward moral emotion witnessing virtue prosocial motivation warm chest openness behavioral effects",
    },
    {
        "id": "grit_perseverance",
        "name": "Grit and long-term perseverance of effort",
        "domain": "individual_variation",
        "wikipedia": "Grit (personality trait)",
        "kagi_query": "grit Duckworth perseverance passion long-term goals consistency effort conscientiousness behavioral outcomes achievement",
    },
    {
        "id": "boredom_proneness",
        "name": "Boredom proneness and sensation seeking",
        "domain": "individual_variation",
        "wikipedia": "Boredom proneness",
        "kagi_query": "boredom proneness sensation seeking Zuckerman Farmer Sundberg low arousal risk taking substance use behavioral outcomes",
    },
    {
        "id": "psychological_resilience",
        "name": "Psychological resilience and stress recovery",
        "domain": "threat_affective_priming",
        "wikipedia": "Psychological resilience",
        "kagi_query": "psychological resilience stress recovery Bonanno hardiness Luthar coping mechanisms positive adaptation adversity behavioral outcomes",
    },
    {
        "id": "social_loafing",
        "name": "Social loafing and free-riding in groups",
        "domain": "social_influence_compliance",
        "wikipedia": "Social loafing",
        "kagi_query": "social loafing Latane Williams Harkins 1979 free riding group effort diffusion responsibility individual accountability behavioral evidence",
    },
]

# Quick lookup
SEED_BY_ID = {s["id"]: s for s in SEEDS}

if __name__ == "__main__":
    print(f"Total seeds: {len(SEEDS)}")
    for domain in DOMAINS:
        count = sum(1 for s in SEEDS if s["domain"] == domain)
        print(f"  {domain}: {count}")
